### ISSUE TITLE
rltcss can read scss?

### ISSUE THREAD

**Issue by aloky** [jjlharrison/gulp-rtlcss#14]
Me seem `rtlcss` cant read `scss`

**Comment by oscarhandsome** [comment]
rtlcss rewrite css to css

**Comment by aloky** [comment]
And such an opportunity will appear?

**Comment by jjlharrison** [comment]
Correct, it's called "rtlcss" not "rtlscss".

Normal use of this plugin is to compile LESS or SCSS to CSS first and then convert that into RTL CSS.

See the example in the README.

**Comment by iJadou** [comment]
@jjlharrison usually we work on scss files, if we want to use RTLCSS value directives such as 
``
.example {font-size:16px/*rtl:14px*/;}
``

**Comment by jjlharrison** [comment]
@iJadou You need to make sure your comment directive is making it through to RTLCSS. With SCSS you can use a `/*! */` comment to preserve the comment even when compiling in compressed mode. See https://sass-lang.com/documentation/syntax/comments:
> If a comment begins with /*!, though, it will always be included in the CSS output.

**Comment by iJadou** [comment]
@jjlharrison Thank you, it works. 🌹

**Comment by DeoThemes** [comment]
I'm having the same issue and Sass is removing the comment if it's placed after the value.

This doesn't work even with a "!"
`font-size: 14px/*!rtl:12px*/;`

**Comment by MohammadYounes** [comment]
@DeoThemes see https://rtlcss.com/learn/usage-guide/value-directives/#Tip

**Comment by DeoThemes** [comment]
@MohammadYounes Wow, thanks a lot, it worked :)
