### ISSUE TITLE
Converting (oppositely) rtl to ltr

### ISSUE THREAD

**Issue by MoradHamdy** [jjlharrison/gulp-rtlcss#16]
I'm working on a website which its default direction is RTL. 

I know that **gulp-rtlcss** is used to get the RTL needed changes, but i'm looking forward to do RTL to LTR this time.

So is there some method to do this with **gulp-rtlcss**?

**Comment by jjlharrison** [comment]
Hi @MoradHamdy, This plugin is just a wrapper for [RTLCSS](https://github.com/MohammadYounes/rtlcss) so this would really be a question for that repository.

However,  I did a quick search and found this: MohammadYounes/rtlcss#67. Hope that helps.

**Comment by MoradHamdy** [comment]
Thanks @jjlharrison 

By the way, i have tried the plugin and i found that it makes convert for the direction state. So it converts RTL to LTR and LTR to RTL. That sounds great :)

I appreciate your clarification!
