### ISSUE TITLE
"Drupal" flag to create RTL-only file

### ISSUE THREAD

**Issue by damienmckenna** [jjlharrison/gulp-rtlcss#5]
There's functionality in Drupal's CSS system (https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_add_css/7) that will automatically load an example-rtl.css file for every example.css file if the current page's language is set to RTL. Unlike rtlcss's current assumption that only one of the files will be load, Drupal will load both files, the idea being that the RTL file overrides the LTR file. Would you be willing to entertain an option for this, so that the RTL file would only contain lines that were different from the LTR file?

**Comment by jjlharrison** [comment]
This feature would need to be implemented by MohammadYounes/rtlcss, not gulp-rtlcss.

Such support has been requested before in MohammadYounes/rtlcss#30, but was not accepted.

See [Why make a complete RTL version?](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F).

**Comment by damienmckenna** [comment]
Thanks for the response!
